import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2>
                    <Link href="/products">
                        <a>Products</a>
                    </Link>
                </h2>
                <h2>
                    <Link href="/orders">
                        <a>Orders</a>
                    </Link>
                </h2>
            </main>
        </div>
    );
}
