import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h2 className={styles.title}>
            <Link href="/form">
              <a>Form</a>
            </Link>
          </h2>
          <h2 className={styles.title}>
            <Link href="/orders">
              <a>Orders</a>
            </Link>
          </h2>
      </main>
    </div>
  )
}
